### ISSUE TITLE
IPv6 adresses lead to yaml error

### ISSUE THREAD

**Issue by bjo81** [LINKIWI/dotproxy#2]
It's not possible to use IPv6-adresses. The following config leads to `panic: config: error parsing config: err=yaml: line 6: did not find expected key`

```
metrics:
  statsd:
    addr: localhost:8125
    sample_rate: 1.0
listener:
  tcp:
    addr: [2a07:59c6:eeff:20:ba27:ebff:fef7:7a6c]:53
    read_timeout: 5s
    write_timeout: 5s
  udp:
    addr: [2a07:59c6:eeff:20:ba27:ebff:fef7:7a6c]:53
    max_concurrent_connections: 64
    write_timeout: 5s
upstream:
  load_balancing_policy: RoundRobin
  max_connection_retries: 10
  servers:
    - addr: 194.59.205.151:853
      server_name: dns.schafweide.org
      connection_pool_size: 8
      connect_timeout: 100ms
      handshake_timeout: 250ms
      read_timeout: 5s
      write_timeout: 5s
      stale_timeout: 10s
```

**Comment by LINKIWI** [comment]
Ah, you need to surround the address in quotes. YAML is interpreting the brackets as an array.

```yaml
listener:
  tcp:
    addr: '[2a07:59c6:eeff:20:ba27:ebff:fef7:7a6c]:53'
    read_timeout: 5s
    write_timeout: 5s
```
