### ISSUE TITLE
Usage example with pi-hole

### ISSUE THREAD

**Issue by moookino** [LINKIWI/dotproxy#3]
Hi, want to try your nice and fast project to run with pi-hole, but cannot figure out how to use configure and use it properly with provided config

Can you create some example or docker-compose example?

Thanks in advance

**Comment by LINKIWI** [comment]
In Pi-hole configuration, you can uncheck all the existing upstream checkboxes and add a new custom upstream pointing to dotproxy. If dotproxy is running on a port other than 53 [you can use the `#` operator to specify the port number](https://www.reddit.com/r/pihole/comments/8texu7/specify_port_for_upstream_when_using_cloudflared/). This will cause Pi-hole to forward all requests to dotproxy, and dotproxy will take care of talking to public upstream servers.

I'm not sure how docker-compose would help here, what exactly are you looking for?

**Comment by moookino** [comment]
@LINKIWI i've found DoH solution for pi-hole + traefik as reverse proxy, so i'm trying to figure out same way for you project in order to make it more popular also.
[https://github.com/ngalayko/server/blob/master/compose/arm32/docker-compose.dns.yaml](url)

So here is the setup, but i'm not sure it's correct as you mentioned in your comment
```
version: "3"
services:
  dotproxy:
    container_name: dotproxy
    volumes:
      - ./config:/config
    ports:
      - "7012:7012"
      - "7012:7012/udp"
    image: antilax3/dotproxy
    labels:
      - "traefik.enable=true"
      - "traefik.network=dns_proxy"
      - "traefik.backend=dotproxy"
      - "traefik.frontend.rule=Host:c.pihole.example.com"
      - "traefik.port=8125"
    networks:
      - proxy

  pihole:
    container_name: pihole
    domainname: example.com
    hostname: pihole
    image: pihole/pihole:latest
    dns:
     - 127.0.0.1
     - 1.1.1.1
    restart: unless-stopped
    networks:
     - proxy
    volumes:
      - ./pihole/pihole:/etc/pihole
      - ./pihole/pihole.log:/var/log/pihole.log
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
      - ./pihole/dhcp.leases:/etc/pihole/dhcp.leases
    cap_add:
      - NET_ADMIN
    environment:
       - ServerIP=IP
       - ServerIPv6=IPv6
       - PROXY_LOCATION=pihole
       - VIRTUAL_HOST=pihole.example.com
       - VIRTUAL_PORT=80
       - TZ="Timezone"
       - WEBPASSWORD=PIHOLEWEBPASSWORD
       - DNS1=127.0.0.1
       - DNS2=1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.network=dns_proxy"
      - "traefik.port=80"
networks:
  proxy:
    external: true
```

what do you think about this type of application for your solution?

**Comment by LINKIWI** [comment]
So you are trying to package Pi-hole and dotproxy together in a docker compose file? Seems like it should work, though I don't use Docker in any of my production environments so I can't help test. I'm closing this issue as there does not seem to be any specific action item here.

**Comment by nightah** [comment]
@moookino this can be done a couple ways:
1. Set your dotproxy to `network_mode: host` and update your Pi-Hole DNS to your Docker Host IP (replace \<IP>). 
```yml
version: "3"
services:
  dotproxy:
    container_name: dotproxy
    volumes:
      - ./config:/config
    ports:
      - "7012:7012"
      - "7012:7012/udp"
    image: antilax3/dotproxy
    labels:
      - "traefik.enable=true"
      - "traefik.network=dns_proxy"
      - "traefik.backend=dotproxy"
      - "traefik.frontend.rule=Host:c.pihole.example.com"
      - "traefik.port=8125"
    network_mode: host

  pihole:
    container_name: pihole
    domainname: example.com
    hostname: pihole
    image: pihole/pihole:latest
    dns:
     - 127.0.0.1
     - 1.1.1.1
    restart: unless-stopped
    networks:
     - proxy
    volumes:
      - ./pihole/pihole:/etc/pihole
      - ./pihole/pihole.log:/var/log/pihole.log
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
      - ./pihole/dhcp.leases:/etc/pihole/dhcp.leases
    cap_add:
      - NET_ADMIN
    environment:
       - ServerIP=IP
       - ServerIPv6=IPv6
       - PROXY_LOCATION=pihole
       - VIRTUAL_HOST=pihole.example.com
       - VIRTUAL_PORT=80
       - TZ="Timezone"
       - WEBPASSWORD=PIHOLEWEBPASSWORD
       - DNS1=<IP>#7012
       - DNS2=no
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.network=dns_proxy"
      - "traefik.port=80"
networks:
  proxy:
    external: true
```

2. Assuming your Docker stack that hosts dotproxy and pihole has a subnet of `172.18.0.0/16` hardcode an IP for dotproxy (i've used 172.18.0.254 in the below example) and specify that in your `docker-compose.yml` for pihole, also ensure that you replace <COMPOSE_STACK> with the name of the folder that houses said compose file.
```yml
version: "3"
services:
  dotproxy:
    container_name: dotproxy
    volumes:
      - ./config:/config
    ports:
      - "7012:7012"
      - "7012:7012/udp"
    image: antilax3/dotproxy
    labels:
      - "traefik.enable=true"
      - "traefik.network=dns_proxy"
      - "traefik.backend=dotproxy"
      - "traefik.frontend.rule=Host:c.pihole.example.com"
      - "traefik.port=8125"
    networks:
      <COMPOSE_STACK>_default:
        ipv4_address: 172.18.0.254
      proxy:
        aliases:
          - dotproxy

  pihole:
    container_name: pihole
    domainname: example.com
    hostname: pihole
    image: pihole/pihole:latest
    dns:
     - 127.0.0.1
     - 1.1.1.1
    restart: unless-stopped
    networks:
     - proxy
    volumes:
      - ./pihole/pihole:/etc/pihole
      - ./pihole/pihole.log:/var/log/pihole.log
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
      - ./pihole/dhcp.leases:/etc/pihole/dhcp.leases
    cap_add:
      - NET_ADMIN
    environment:
       - ServerIP=IP
       - ServerIPv6=IPv6
       - PROXY_LOCATION=pihole
       - VIRTUAL_HOST=pihole.example.com
       - VIRTUAL_PORT=80
       - TZ="Timezone"
       - WEBPASSWORD=PIHOLEWEBPASSWORD
       - DNS1=172.18.0.254#7012
       - DNS2=no
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.network=dns_proxy"
      - "traefik.port=80"
networks:
  proxy:
    external: true
```
